services:
  ldap:
    image: test-ldap:latest
    build: src/ldap
    logging:
      options:
         tag: "ldap"
    networks:
     - back

  idp:
    image: test-idp:latest
    build: src/idp
    logging:
      options:
         tag: "idp"
    networks:
     - front
     - back
    ports:
     - "8443:443"

networks:
  front:
  back:    
